### ISSUE TITLE
assets/scene_Playground.h: No such file or directory

### ISSUE THREAD

**Issue by kimpark2000** [matthewcpp/framework64#4]
The file named 'scene.Playground.h' cannot be found.
I wanted to make a fun n64 game for Framework 64, but this error occurred.
What do I need to install for the scene.Playground.h file to appear in the asset folder? T_T
I'm curious about the solution to that.

The error log is like this:

[main] Building folder: /workspaces/mygame/build_n64_libultra 
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /workspaces/mygame/build_n64_libultra --config Release --target mygame -j 22 --
[build] [ 93%] Built target framework64
[build] [ 94%] Building C object src/CMakeFiles/mygame.dir/game.c.obj
[build] /workspaces/mygame/src/game.c:6:10: fatal error: assets/scene_Playground.h: No such file or directory
[build]     6 | #include "assets/scene_Playground.h"
[build]       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
[build] compilation terminated.
[build] make[3]: *** [src/CMakeFiles/mygame.dir/build.make:63: src/CMakeFiles/mygame.dir/game.c.obj] Error 1
[build] make[2]: *** [CMakeFiles/Makefile2:180: src/CMakeFiles/mygame.dir/all] Error 2
[build] make[1]: *** [CMakeFiles/Makefile2:187: src/CMakeFiles/mygame.dir/rule] Error 2
[build] make: *** [Makefile:131: mygame] Error 2
[proc] The command: /usr/bin/cmake --build /workspaces/mygame/build_n64_libultra --config Release --target mygame -j 22 -- exited with code: 2
[driver] Build completed: 00:00:00.093
[build] Build finished with exit code 2

**Comment by kimpark2000** [comment]
![Uploading picture2.png…]()

**Comment by kimpark2000** [comment]
![picture2](https://github.com/user-attachments/assets/07316c34-21c2-4568-b90e-0f0b394d378b)

**Comment by kimpark2000** [comment]
![picture](https://github.com/user-attachments/assets/d549dc2b-2a5c-4417-9aac-ce64c60889cb)

I also attached a photo above.
I've been struggling all day with the scene.Playground.h file.
I am waiting for this to be resolved please.

**Comment by kivan117** [comment]
Did you run the asset prep step before trying to build? It should create those .h files

I believe the command for the N64 build is still

```
npm run prepare_assets n64_libultra
```


In general, your asset workflow would be:

- Create your base assets (models, textures, etc)
- Update the assets manifest file as needed so that they can be converted properly.
- Prepare assets script (converts them for use on the target platform and creates necessary header files for their use in code)
- Then finally build.


Specifics for the assets and the manifest file are in the repo wiki

**Comment by kimpark2000** [comment]
I just solved it. Thank you  ^^
